title: Just another bioinf blog
description: Michael Roach's blog
show_downloads: false
google_analytics:
theme: jekyll-theme-midnight
excerpt_separator: <!--more-->

# Colour palette for future reference
# https://coolors.co/ffb997-f67e7d-843b62-0b032d-74546a

